import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}): any {
  return (
    <html lang="en">
      <head>
        <title>Music Player</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
